### ISSUE TITLE
How can I use the lonpos 3d solver?

### ISSUE THREAD

**Issue by wd5dw** [ArnoHue/fun#1]
Can you tell me how to use for lonpos 3d solver?

**Comment by ArnoHue** [comment]
- Create a new .NET Console Application project in Visual Studio
- Add Lonpos.cs to project
- Run the project. This will print Lonpos shapes and their rotated variants
- Adapt initial pyramid definition in Solve() method, e.g:
```
// wizard level / #101
pyramid.MergeIntoLayer(green.GetRotations().ElementAt(5), 0, 3, 0);
pyramid.MergeIntoLayer(red.GetRotations().ElementAt(2), 0, 0, 0);
availFigures.Remove(green);
availFigures.Remove(red);
```
- Run project again, press any key to start solving

**Comment by ArnoHue** [comment]
I have now added Visual Studio solution and project files
